workflows:
  my-workflow:
    environment:
      flutter: default
    scripts:
      - name: Build Android App Bundle
        working_directory: android
        script: /android/gradlew bundleRelease
    artifacts:
      - build/**/outputs/bundle/**/*.aab